In [33]:
#Importing the libraries

'''Numpy: Numpy Python library is used for including any type of mathematical operation in the code.

Matplotlib: The second library is matplotlib, which is a Python 2D plotting library,
and with this library,we need to import a sub-library pyplot.

Pandas: The last library is the Pandas library, which is one of the most famous Python libraries and used for importing and managing the datasets.
It is an open-source data manipulation and analysis library.'''

'Numpy: Numpy Python library is used for including any type of mathematical operation in the code.\n\nMatplotlib: The second library is matplotlib, which is a Python 2D plotting library,\nand with this library,we need to import a sub-library pyplot.\n\nPandas: The last library is the Pandas library, which is one of the most famous Python libraries and used for importing and managing the datasets.\nIt is an open-source data manipulation and analysis library.'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Importing the dataset

In [5]:
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [34]:
#Extracting dependent and independent variables:
'''it is important to distinguish the matrix of features (independent variables) and 
dependent variables from dataset.In our dataset, there are three independent variables that 
are Country,Age, and Salary, and one is a dependent variable which is Purchased.'''

#Extracting dependent variable:
'''To extract an independent variable, we will use iloc[ ] method of Pandas library. 
It is used to extract the required rows and columns from the dataset.'''

'To extract an independent variable, we will use iloc[ ] method of Pandas library. \nIt is used to extract the required rows and columns from the dataset.'

In [7]:
X = dataset.iloc[:, :-1].values
X

array([['India', 34.0, 92000.0],
       ['Sri lanka', 22.0, 25000.0],
       ['China', 31.0, 74000.0],
       ['Sri lanka', 29.0, nan],
       ['China', 55.0, 98000.0],
       ['India', 24.0, 30000.0],
       ['Sri lanka', 28.0, 40000.0],
       ['India', nan, 60000.0],
       ['China', 51.0, 89000.0],
       ['India', 44.0, 78000.0],
       ['Sri lanka', 21.0, 20000.0],
       ['China', 25.0, 30000.0],
       ['India', 33.0, 45000.0],
       ['India', 42.0, 65000.0],
       ['Sri lanka', 33.0, 22000.0]], dtype=object)

In [8]:
#Extracting dependent variable:

y = dataset.iloc[:, -1].values
y

array(['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [9]:
#handling missing data (Replacing missing data with the mean value)  
#By deleting the particular row or By calculating the mean: 

from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  

In [10]:
#Fitting imputer object to the independent variables x.

imputer.fit(X[:, 1:3]) 

SimpleImputer()

In [11]:
#Replacing missing data with the calculated mean value  

X[:, 1:3] = imputer.transform(X[:, 1:3])

In [12]:
print(X)

[['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 54857.142857142855]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' 33.714285714285715 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]


In [14]:
#Encoding Categorical data:
#Encoding the Independent Variable

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
print(X)

[[0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 29.0 54857.142857142855]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 1.0 0.0 24.0 30000.0]
 [0.0 0.0 1.0 28.0 40000.0]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 0.0 1.0 33.0 22000.0]]


In [18]:
#Encoding the Dependent Variable

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [20]:
print(y)

[1 1 1 0 1 0 0 0 1 1 0 1 1 1 0]


In [21]:
#Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [23]:
print(X_train)

[[1.0 0.0 0.0 31.0 74000.0]
 [0.0 0.0 1.0 21.0 20000.0]
 [1.0 0.0 0.0 55.0 98000.0]
 [0.0 0.0 1.0 22.0 25000.0]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 1.0 0.0 34.0 92000.0]
 [0.0 0.0 1.0 33.0 22000.0]
 [0.0 1.0 0.0 44.0 78000.0]
 [1.0 0.0 0.0 51.0 89000.0]
 [0.0 1.0 0.0 33.0 45000.0]
 [1.0 0.0 0.0 25.0 30000.0]
 [0.0 1.0 0.0 24.0 30000.0]]


In [24]:
print(X_test)

[[0.0 0.0 1.0 29.0 54857.142857142855]
 [0.0 1.0 0.0 33.714285714285715 60000.0]
 [0.0 0.0 1.0 28.0 40000.0]]


In [25]:
print(y_train)

[1 0 1 1 1 1 0 1 1 1 1 0]


In [26]:
print(y_test)

[0 0 0]


In [27]:
#Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [29]:
print(X_train)

[[1.0 0.0 0.0 -0.3323561357816283 0.637555294512461]
 [0.0 0.0 1.0 -1.2598616309861719 -1.2403348456878782]
 [1.0 0.0 0.0 1.8936570527092762 1.4721731346015006]
 [0.0 0.0 1.0 -1.1671110814657175 -1.0664561290026617]
 [0.0 1.0 0.0 0.6878999089433696 0.3245736044790711]
 [0.0 1.0 0.0 -0.054104487220265264 1.2635186745792406]
 [0.0 0.0 1.0 -0.14685503674071962 -1.1707833590137917]
 [0.0 1.0 0.0 0.8734010079842783 0.7766582678606342]
 [1.0 0.0 0.0 1.5226548546274588 1.1591914445681106]
 [0.0 1.0 0.0 -0.14685503674071962 -0.3709412622617953]
 [1.0 0.0 0.0 -0.8888594329043545 -0.892577412317445]
 [0.0 1.0 0.0 -0.9816099824248089 -0.892577412317445]]


In [30]:
print(X_test)

[[0.0 0.0 1.0 -0.5178572348225371 -0.02815179222522553]
 [0.0 1.0 0.0 -0.08060464422610927 0.15069488779385445]
 [0.0 0.0 1.0 -0.6106077843429915 -0.544819978947012]]
