In [1]:
# Step-1: Data Pre-processing Step:

In [2]:
#importing Libraries

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [3]:
#importing datasets

In [4]:
dataset = pd.read_csv('50_Startups.csv')

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [8]:
dataset.shape

(50, 5)

In [9]:
#Extracting dependent and independent Variables:

In [12]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

In [13]:
# Encoding Dummy Variables:

In [14]:
#Categorical Data

In [29]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
labelencoder_x = LabelEncoder()

In [31]:
x[:,3] = labelencoder_x.fit_transform(x[:,3])

In [32]:
ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
X = ct.fit_transform(x)

In [35]:
#avoiding the dummy variable trap:  
x = x[:, 1:]  

In [36]:
# Splitting the dataset into training and test set. 

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=0) 

In [37]:
print(y_test)

[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


In [38]:
print(X_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


In [39]:
#Step: 2- Fitting our MLR model to the Training set:

In [40]:
#Fitting the MLR model to the training set:

from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(X_train, y_train)  

LinearRegression()

In [41]:
# Step: 3- Prediction of Test set results:

In [42]:
#Predicting the Test set result;  

y_pred= regressor.predict(X_test)  

In [43]:
print(y_pred)

[103015.20159796 132582.27760816 132447.73845174  71976.09851258
 178537.48221055 116161.24230166  67851.69209676  98791.73374686
 113969.43533013 167921.06569551]


In [44]:
print('Train Score: ', regressor.score(X_train, y_train))  
print('Test Score: ', regressor.score(X_test, y_test))  

Train Score:  0.9501847627493607
Test Score:  0.9347068473282303
