In [32]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  

In [33]:
dataset = pd.read_csv('train.csv')

In [34]:
dataset.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [35]:
dataset.shape

(42000, 785)

In [36]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,0].values

In [37]:
print(x)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [38]:
print(y)

[1 0 1 ... 7 6 9]


In [39]:
# Splitting the dataset into training and test set. 

from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 1/3, random_state=0) 

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [43]:
#predictions

y_pred = model.predict(x_test)

In [44]:
#Model evaluation
from sklearn.metrics import accuracy_score,confusion_matrix

In [45]:
cfm = confusion_matrix(y_test,y_pred)

In [46]:
cfm

array([[1349,    3,   24,    4,    2,    0,    0,    0,    0,    0],
       [   0, 1560,   22,    2,    0,    0,    0,    0,    0,    0],
       [  15,   17, 1349,   23,   13,    5,    3,    2,    0,    1],
       [  14,   10,   31, 1360,    6,   22,    0,    6,    0,    0],
       [   5,   10,   10,    8, 1297,    7,   14,    6,    0,    0],
       [   4,    5,    0,   21,   12, 1165,   19,    4,    9,    3],
       [   0,    0,    3,    0,   12,   24, 1355,    0,    3,    1],
       [   0,    0,    0,    0,    9,    9,    5, 1428,   16,   14],
       [   0,    0,    0,    0,    0,   10,   16,    2, 1277,   25],
       [   0,    0,    0,    0,    0,    5,    0,   10,   19, 1315]],
      dtype=int64)

In [47]:
accuracy_score(y_test,y_pred)

0.9610714285714286

In [48]:
#Fitting the MLR model to the training set:

from sklearn.linear_model import LinearRegression  
regressor= LinearRegression()  
regressor.fit(x_train, y_train)  

LinearRegression()

In [49]:
y_pred= regressor.predict(x_test)  

In [50]:
print(y_pred)

[3. 6. 9. ... 4. 8. 1.]


In [52]:
print('Train Score: ', regressor.score(x_train, y_train))  
print('Test Score: ', regressor.score(x_test, y_test))  

Train Score:  1.0
Test Score:  0.9990747152508285
